branch-defaults:
  master:
    environment: dbrunner-prod
global:
  application_name: dbrunner
  default_ec2_keyname: aws-eb
  default_platform: 64bit Amazon Linux 2016.03 v2.1.3 running Python 3.4
  default_region: us-west-2
  profile: null
  sc: git
